// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bjj-directory/Academy.tsx": () => import("../components/mockups/bjj-directory/Academy.tsx"),
  "./components/mockups/bjj-directory/Blue.tsx": () => import("../components/mockups/bjj-directory/Blue.tsx"),
  "./components/mockups/bjj-directory/Championship.tsx": () => import("../components/mockups/bjj-directory/Championship.tsx"),
  "./components/mockups/bjj-directory/Combat.tsx": () => import("../components/mockups/bjj-directory/Combat.tsx"),
  "./components/mockups/bjj-directory/Crimson.tsx": () => import("../components/mockups/bjj-directory/Crimson.tsx"),
  "./components/mockups/bjj-directory/MobileBlue.tsx": () => import("../components/mockups/bjj-directory/MobileBlue.tsx"),
  "./components/mockups/bjj-directory/MobileCrimson.tsx": () => import("../components/mockups/bjj-directory/MobileCrimson.tsx"),
  "./components/mockups/bjj-directory/MobileOrange.tsx": () => import("../components/mockups/bjj-directory/MobileOrange.tsx")
};
